// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sparklytix.socialme.model;

import com.sparklytix.socialme.model.SocialUserRegistrationDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SocialUserRegistrationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SocialUserRegistrationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SocialUserRegistrationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SocialUserRegistrationIntegrationTest: @Transactional;
    
    @Autowired
    private SocialUserRegistrationDataOnDemand SocialUserRegistrationIntegrationTest.dod;
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testCountSocialUserRegistrations() {
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", dod.getRandomSocialUserRegistration());
        long count = SocialUserRegistration.countSocialUserRegistrations();
        Assert.assertTrue("Counter for 'SocialUserRegistration' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testFindSocialUserRegistration() {
        SocialUserRegistration obj = dod.getRandomSocialUserRegistration();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to provide an identifier", id);
        obj = SocialUserRegistration.findSocialUserRegistration(id);
        Assert.assertNotNull("Find method for 'SocialUserRegistration' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SocialUserRegistration' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testFindAllSocialUserRegistrations() {
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", dod.getRandomSocialUserRegistration());
        long count = SocialUserRegistration.countSocialUserRegistrations();
        Assert.assertTrue("Too expensive to perform a find all test for 'SocialUserRegistration', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SocialUserRegistration> result = SocialUserRegistration.findAllSocialUserRegistrations();
        Assert.assertNotNull("Find all method for 'SocialUserRegistration' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SocialUserRegistration' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testFindSocialUserRegistrationEntries() {
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", dod.getRandomSocialUserRegistration());
        long count = SocialUserRegistration.countSocialUserRegistrations();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SocialUserRegistration> result = SocialUserRegistration.findSocialUserRegistrationEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SocialUserRegistration' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SocialUserRegistration' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testFlush() {
        SocialUserRegistration obj = dod.getRandomSocialUserRegistration();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to provide an identifier", id);
        obj = SocialUserRegistration.findSocialUserRegistration(id);
        Assert.assertNotNull("Find method for 'SocialUserRegistration' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySocialUserRegistration(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SocialUserRegistration' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testMergeUpdate() {
        SocialUserRegistration obj = dod.getRandomSocialUserRegistration();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to provide an identifier", id);
        obj = SocialUserRegistration.findSocialUserRegistration(id);
        boolean modified =  dod.modifySocialUserRegistration(obj);
        Integer currentVersion = obj.getVersion();
        SocialUserRegistration merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SocialUserRegistration' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", dod.getRandomSocialUserRegistration());
        SocialUserRegistration obj = dod.getNewTransientSocialUserRegistration(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SocialUserRegistration' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SocialUserRegistration' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SocialUserRegistrationIntegrationTest.testRemove() {
        SocialUserRegistration obj = dod.getRandomSocialUserRegistration();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserRegistration' failed to provide an identifier", id);
        obj = SocialUserRegistration.findSocialUserRegistration(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SocialUserRegistration' with identifier '" + id + "'", SocialUserRegistration.findSocialUserRegistration(id));
    }
    
}
