// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sparklytix.socialme.model;

import com.sparklytix.socialme.model.SocialUser;
import java.lang.String;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect SocialUserDataOnDemand_Roo_DataOnDemand {
    
    declare @type: SocialUserDataOnDemand: @Component;
    
    private Random SocialUserDataOnDemand.rnd = new SecureRandom();
    
    private List<SocialUser> SocialUserDataOnDemand.data;
    
    public SocialUser SocialUserDataOnDemand.getNewTransientSocialUser(int index) {
        SocialUser obj = new SocialUser();
        setEmailAddress(obj, index);
        setFirstName(obj, index);
        setLastName(obj, index);
        setPassword(obj, index);
        return obj;
    }
    
    public void SocialUserDataOnDemand.setEmailAddress(SocialUser obj, int index) {
        String emailAddress = "emailAddress_" + index;
        obj.setEmailAddress(emailAddress);
    }
    
    public void SocialUserDataOnDemand.setFirstName(SocialUser obj, int index) {
        String firstName = "firstName_" + index;
        obj.setFirstName(firstName);
    }
    
    public void SocialUserDataOnDemand.setLastName(SocialUser obj, int index) {
        String lastName = "lastName_" + index;
        obj.setLastName(lastName);
    }
    
    public void SocialUserDataOnDemand.setPassword(SocialUser obj, int index) {
        String password = "password_" + index;
        obj.setPassword(password);
    }
    
    public SocialUser SocialUserDataOnDemand.getSpecificSocialUser(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        SocialUser obj = data.get(index);
        java.lang.Long id = obj.getId();
        return SocialUser.findSocialUser(id);
    }
    
    public SocialUser SocialUserDataOnDemand.getRandomSocialUser() {
        init();
        SocialUser obj = data.get(rnd.nextInt(data.size()));
        java.lang.Long id = obj.getId();
        return SocialUser.findSocialUser(id);
    }
    
    public boolean SocialUserDataOnDemand.modifySocialUser(SocialUser obj) {
        return false;
    }
    
    public void SocialUserDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = SocialUser.findSocialUserEntries(from, to);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'SocialUser' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<com.sparklytix.socialme.model.SocialUser>();
        for (int i = 0; i < 10; i++) {
            SocialUser obj = getNewTransientSocialUser(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> it = e.getConstraintViolations().iterator(); it.hasNext();) {
                    ConstraintViolation<?> cv = it.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
