// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sparklytix.socialme.model;

import com.sparklytix.socialme.model.SocialUserScrapBookDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SocialUserScrapBookIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SocialUserScrapBookIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SocialUserScrapBookIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SocialUserScrapBookIntegrationTest: @Transactional;
    
    @Autowired
    private SocialUserScrapBookDataOnDemand SocialUserScrapBookIntegrationTest.dod;
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testCountSocialUserScrapBooks() {
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", dod.getRandomSocialUserScrapBook());
        long count = SocialUserScrapBook.countSocialUserScrapBooks();
        Assert.assertTrue("Counter for 'SocialUserScrapBook' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testFindSocialUserScrapBook() {
        SocialUserScrapBook obj = dod.getRandomSocialUserScrapBook();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to provide an identifier", id);
        obj = SocialUserScrapBook.findSocialUserScrapBook(id);
        Assert.assertNotNull("Find method for 'SocialUserScrapBook' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SocialUserScrapBook' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testFindAllSocialUserScrapBooks() {
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", dod.getRandomSocialUserScrapBook());
        long count = SocialUserScrapBook.countSocialUserScrapBooks();
        Assert.assertTrue("Too expensive to perform a find all test for 'SocialUserScrapBook', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SocialUserScrapBook> result = SocialUserScrapBook.findAllSocialUserScrapBooks();
        Assert.assertNotNull("Find all method for 'SocialUserScrapBook' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SocialUserScrapBook' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testFindSocialUserScrapBookEntries() {
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", dod.getRandomSocialUserScrapBook());
        long count = SocialUserScrapBook.countSocialUserScrapBooks();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SocialUserScrapBook> result = SocialUserScrapBook.findSocialUserScrapBookEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SocialUserScrapBook' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SocialUserScrapBook' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testFlush() {
        SocialUserScrapBook obj = dod.getRandomSocialUserScrapBook();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to provide an identifier", id);
        obj = SocialUserScrapBook.findSocialUserScrapBook(id);
        Assert.assertNotNull("Find method for 'SocialUserScrapBook' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySocialUserScrapBook(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SocialUserScrapBook' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testMergeUpdate() {
        SocialUserScrapBook obj = dod.getRandomSocialUserScrapBook();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to provide an identifier", id);
        obj = SocialUserScrapBook.findSocialUserScrapBook(id);
        boolean modified =  dod.modifySocialUserScrapBook(obj);
        Integer currentVersion = obj.getVersion();
        SocialUserScrapBook merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SocialUserScrapBook' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", dod.getRandomSocialUserScrapBook());
        SocialUserScrapBook obj = dod.getNewTransientSocialUserScrapBook(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SocialUserScrapBook' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SocialUserScrapBook' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SocialUserScrapBookIntegrationTest.testRemove() {
        SocialUserScrapBook obj = dod.getRandomSocialUserScrapBook();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUserScrapBook' failed to provide an identifier", id);
        obj = SocialUserScrapBook.findSocialUserScrapBook(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SocialUserScrapBook' with identifier '" + id + "'", SocialUserScrapBook.findSocialUserScrapBook(id));
    }
    
}
