// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.sparklytix.socialme.model;

import com.sparklytix.socialme.model.SocialUserDataOnDemand;
import java.lang.Integer;
import java.lang.Long;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect SocialUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: SocialUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: SocialUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: SocialUserIntegrationTest: @Transactional;
    
    @Autowired
    private SocialUserDataOnDemand SocialUserIntegrationTest.dod;
    
    @Test
    public void SocialUserIntegrationTest.testCountSocialUsers() {
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", dod.getRandomSocialUser());
        long count = SocialUser.countSocialUsers();
        Assert.assertTrue("Counter for 'SocialUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void SocialUserIntegrationTest.testFindSocialUser() {
        SocialUser obj = dod.getRandomSocialUser();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to provide an identifier", id);
        obj = SocialUser.findSocialUser(id);
        Assert.assertNotNull("Find method for 'SocialUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'SocialUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void SocialUserIntegrationTest.testFindAllSocialUsers() {
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", dod.getRandomSocialUser());
        long count = SocialUser.countSocialUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'SocialUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<SocialUser> result = SocialUser.findAllSocialUsers();
        Assert.assertNotNull("Find all method for 'SocialUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'SocialUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void SocialUserIntegrationTest.testFindSocialUserEntries() {
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", dod.getRandomSocialUser());
        long count = SocialUser.countSocialUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<SocialUser> result = SocialUser.findSocialUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'SocialUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'SocialUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void SocialUserIntegrationTest.testFlush() {
        SocialUser obj = dod.getRandomSocialUser();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to provide an identifier", id);
        obj = SocialUser.findSocialUser(id);
        Assert.assertNotNull("Find method for 'SocialUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifySocialUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'SocialUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserIntegrationTest.testMergeUpdate() {
        SocialUser obj = dod.getRandomSocialUser();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to provide an identifier", id);
        obj = SocialUser.findSocialUser(id);
        boolean modified =  dod.modifySocialUser(obj);
        Integer currentVersion = obj.getVersion();
        SocialUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'SocialUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void SocialUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", dod.getRandomSocialUser());
        SocialUser obj = dod.getNewTransientSocialUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'SocialUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'SocialUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void SocialUserIntegrationTest.testRemove() {
        SocialUser obj = dod.getRandomSocialUser();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'SocialUser' failed to provide an identifier", id);
        obj = SocialUser.findSocialUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'SocialUser' with identifier '" + id + "'", SocialUser.findSocialUser(id));
    }
    
}
